name: Deploy EKS with Helm

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes CLI (kubectl)
        uses: azure/setup-kubectl@v1
        with:
          version: "v1.30.0" 

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.16.1" 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name janocluster --region ap-southeast-1

      - name: Deploy with Helm
        run: |
          helm upgrade --install blockscout ./eks-helm-chart \
            --namespace default \
            --values ./eks-helm-chart/values.yaml
